var welcome = "Hello there";
console.log(welcome);
var isAwesome = true;
console.log(isAwesome);
var iAmaNumbah = 100;
console.log(iAmaNumbah);
var pi = 3.141592;
console.log(pi);
iAmaNumbah = 90;
var dynamic = true;
dynamic = 5;
var a = 50;
a = a + 4;
console.log(a);
var b = 12;
b = b - 4;
console.log(b);
var d = 12;
d /= 3;
console.log(d);
var e = 30;
e %= 7;
console.log(e);
var f = 12;
f++;
console.log(f);
var g = 12;
g--;
console.log(g);
var h = 10;
console.log(h);
console.log(h++);
console.log(h);
var i = 10;
console.log(i);
console.log(++i);
console.log(i);
